
vagrant-local:
    vm:
        network:
            # Set new IP if you have multiple Vagrant machines running
            private_network: 10.0.1.100
            forwarded_port: 
                host: '8080'
                guest: '80'
            bridge_type: 'en0: Wi-Fi (AirPort)'
    project:
        #Setup project name and location folder
        name: 
        location: ./
    drupal:
        # If there is database dump set its name
        database_filename: 
